#!/usr/bin/env php
<?php

declare(strict_types=1);

use Nikanzo\Core\Console\Command\DbMigrateCommand;
use Nikanzo\Core\Console\Command\DbSeedCommand;
use Nikanzo\Core\Console\Command\MakeControllerCommand;
use Nikanzo\Core\Console\Command\MakeUsecaseCommand;
use Nikanzo\Core\Console\Command\RouteCacheCommand;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$config = [
    'name' => 'NikanzoPHP',
    'version' => '0.2.0',
];
$configFile = __DIR__ . '/config/cli.php';
if (is_file($configFile)) {
    $loaded = require $configFile;
    if (is_array($loaded)) {
        $config = array_merge($config, $loaded);
    }
}

$application = new Application($config['name'], $config['version']);
$basePath = __DIR__;

$application->add(new MakeControllerCommand($basePath));
$application->add(new MakeUsecaseCommand($basePath));
$application->add(new DbMigrateCommand($basePath));
$application->add(new DbSeedCommand($basePath));
$application->add(new RouteCacheCommand($basePath));

$application->run();